module.exports = {
    "login": "genarot",
    "id": 15189582,
    "node_id": "MDQ6VXNlcjE1MTg5NTgy",
    "avatar_url": "https://avatars2.githubusercontent.com/u/15189582?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/genarot",
    "html_url": "https://github.com/genarot",
    "followers_url": "https://api.github.com/users/genarot/followers",
    "following_url": "https://api.github.com/users/genarot/following{/other_user}",
    "gists_url": "https://api.github.com/users/genarot/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/genarot/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/genarot/subscriptions",
    "organizations_url": "https://api.github.com/users/genarot/orgs",
    "repos_url": "https://api.github.com/users/genarot/repos",
    "events_url": "https://api.github.com/users/genarot/events{/privacy}",
    "received_events_url": "https://api.github.com/users/genarot/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Genaro Tinoco",
    "company": "@AtomicDevelopers ",
    "blog": "",
    "location": "Nicaragua",
    "email": null,
    "hireable": true,
    "bio": null,
    "public_repos": 52,
    "public_gists": 5,
    "followers": 3,
    "following": 18,
    "created_at": "2015-10-19T05:15:44Z",
    "updated_at": "2020-03-31T16:32:52Z"
  }