module.exports = {
    "login": "jperez",
    "id": 999247,
    "node_id": "MDQ6VXNlcjk5OTI0Nw==",
    "avatar_url": "https://avatars2.githubusercontent.com/u/999247?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jperez",
    "html_url": "https://github.com/jperez",
    "followers_url": "https://api.github.com/users/jperez/followers",
    "following_url": "https://api.github.com/users/jperez/following{/other_user}",
    "gists_url": "https://api.github.com/users/jperez/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jperez/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jperez/subscriptions",
    "organizations_url": "https://api.github.com/users/jperez/orgs",
    "repos_url": "https://api.github.com/users/jperez/repos",
    "events_url": "https://api.github.com/users/jperez/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jperez/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Jorge Pérez",
    "company": "SICOP",
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 1,
    "public_gists": 0,
    "followers": 0,
    "following": 1,
    "created_at": "2011-08-23T15:21:59Z",
    "updated_at": "2015-04-07T15:02:06Z"
  }